### ISSUE TITLE
How to use http client with just URL? Not host/port?

### ISSUE THREAD

**Issue by jjohnson5253** [jsonrpcx/json-rpc-cxx#29]
In the other repo [json-rpc-cpp](https://github.com/cinemast/libjson-rpc-cpp), I was able to run this simple code to use JSON-rpc with the ethereum network:

```cpp
int main() {
  // use ethereum main net node
  string url = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161";
  string method = "eth_blockNumber";
  HttpClient client(url);
  Client c(client);

  // send empty parameters for eth_blockNumber
  Json::Value params;

  try {
    // send eth_blockNumber as RPC and print result to console
    cout << c.CallMethod(method, params) << endl;
  } catch (JsonRpcException &e) {
    cerr << e.what() << endl;
  }
}
```

I'm struggling to figure out how to do that with this repo, since the client creation requires a host/port combo. The other repo just needed a URL. For example, in this repo I'm trying to follow the warehouse example sort of by using CppHttpLibClientConnector.h (which I had to pull from examples since it wasn't in the include directory...)

```cpp
  // use ethereum main net node from infura (got from metamask)
  string url = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161";
  string method = "eth_blockNumber";

  CppHttpLibClientConnector httpClient(url,0); // Is there a way I can use a URL here???
  JsonRpcClient client(httpClient, version::v2);

  client.CallMethod<bool>(0, method, {});
```

Maybe I'm missing something in the repo, but does anyone know how I can create a client object in this repo with just a URL instead of host/port combo?

**Comment by cinemast** [comment]
Hi!

First the http code is in the example directory, because it is an example and not part of this library, it should guide you to get an idea how you can integrate the connects that you need. 
json-rpc-cxx handles only the JSON-RPC 2.0 protocol, and not the underlying connection protocols. 

The http example uses [cpp-httplib](https://github.com/yhirose/cpp-httplib), so regarding its usage, please have a look there.

Regarding the port, https typically runs on port 443, but cpp-httplib also works with URLs only.

**Comment by jjohnson5253** [comment]
Ah ok! I’ll work on this. Maybe I’ll make a pull request for an example that uses a connector for URLs…
